name: "Setup Node.js and install npm dependencies"

inputs:
  token:
    description: "NPM private registry token"
    required: true
  node-version:
    description: "Node.js version"
    required: true
    default: 16

runs:
  using: "composite"
  steps:
    - name: Use Node.js ${{ inputs.node-version }}
      uses: actions/setup-node@v3.5.0
      with:
        node-version: ${{ inputs.node-version }}
        registry-url: "https://npm.pkg.github.com"

    - name: Check npm packages cache
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          ${{ runner.os }}-node-

    - name: Install npm packages
      shell: bash
      run: npm ci
      env:
        NODE_AUTH_TOKEN: ${{ inputs.token }}
