name: "Continuous integration"

on:
  pull_request:
    branches:
      - main

jobs:
  ci:
    name: Format, typecheck, build, test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install npm dependencies
        uses: ./.github/actions/setup

      - name: Check code formatting
        run: npm run format:check

      - name: Typecheck
        run: npm run typecheck

      - name: Build
        run: npm run build

      - name: Test
        run: npm run coverage -- --reporter json --outputFile coverage/report.json

      - name: Monitor coverage
        # if: ! contains(github.event.pull_request.user.login, 'dependabot[bot]')
        uses: slavcodev/coverage-monitor-action@v1
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          coverage_path: "coverage/report.json"
